# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/wizzam/Documents/Vivado/ECE 4401/Lab_6/AXI_VGA_Slave_repo/edit_AXI_VGA_Slave_v1_0.cache/wt} [current_project]
set_property parent.project_path {C:/Users/wizzam/Documents/Vivado/ECE 4401/Lab_6/AXI_VGA_Slave_repo/edit_AXI_VGA_Slave_v1_0.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_repo_paths {
  {c:/Users/wizzam/Documents/Vivado/ECE 4401/Lab_5/ps2lab_master_repo/ps2lab_master_1.0}
  {c:/Users/wizzam/Documents/Vivado/ECE 4401/Lab_5/ps2_repo/ps2_1.0}
  {c:/Users/wizzam/Documents/Vivado/ECE 4401/Lab_5/axi_7seg_ps2_repo/axi_7seg_ps2_1.0}
} [current_project]
update_ip_catalog
set_property ip_output_repo {c:/Users/wizzam/Documents/Vivado/ECE 4401/Lab_6/AXI_VGA_Slave_repo/edit_AXI_VGA_Slave_v1_0.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library "" {
  {C:/Users/wizzam/Documents/Vivado/ECE 4401/Lab_6/AXI_VGA_Slave_repo/AXI_VGA_Slave_1.0/hdl/AXI_VGA_Slave_v1_0_S00_AXI.vhd}
  {C:/Users/wizzam/Documents/Vivado/ECE 4401/Lab_6/AXI_VGA_Slave_repo/AXI_VGA_Slave_1.0/hdl/AXI_VGA_Slave_v1_0.vhd}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/wizzam/Documents/Vivado/ECE 4401/Lab_6/AXI_VGA_Slave_repo/AXI_VGA_Slave_1.0/src/clock_divider.vhd}
  {C:/Users/wizzam/Documents/Vivado/ECE 4401/Lab_6/AXI_VGA_Slave_repo/AXI_VGA_Slave_1.0/src/vga_generator.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top AXI_VGA_Slave_v1_0 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AXI_VGA_Slave_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AXI_VGA_Slave_v1_0_utilization_synth.rpt -pb AXI_VGA_Slave_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
